name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npm install @capacitor/core @capacitor/cli @capacitor/android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Sync Web Assets
        run: |
          # Jar tumcha code main folder madhe asel tar to www madhe copy karel
          if [ ! -d "www" ]; then mkdir www; fi
          cp *.html www/ 2>/dev/null || :
          cp *.css www/ 2>/dev/null || :
          cp *.js www/ 2>/dev/null || :
          
          if [ ! -d "android" ]; then
            npx cap add android
          fi
          npx cap sync android

      - name: Build Android APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CSNDuty-App
          path: android/app/build/outputs/apk/debug/app-debug.apk
